---
plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - spec/integration/**/*

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
