# frozen_string_literal: true

require "fast_mcp"

require_relative "omnifocus_mcp/json_rpc_compat"
OmnifocusMcp::JsonRpcCompat.apply!

require_relative "omnifocus_mcp/version"
require_relative "omnifocus_mcp/logger"
require_relative "omnifocus_mcp/config"
require_relative "omnifocus_mcp/result"
require_relative "omnifocus_mcp/infrastructure"
require_relative "omnifocus_mcp/infrastructure/apple_script"
require_relative "omnifocus_mcp/infrastructure/apple_script_date_builder"
require_relative "omnifocus_mcp/infrastructure/js_embed"
require_relative "omnifocus_mcp/infrastructure/script_runner"
require_relative "omnifocus_mcp/parsers"
require_relative "omnifocus_mcp/parsers/apple_script_envelope"

# Utils have no internal deps and underpin everything else.
require_relative "omnifocus_mcp/utils/apple_script_envelope"
require_relative "omnifocus_mcp/utils/apple_script_helpers"
require_relative "omnifocus_mcp/utils/blank"
require_relative "omnifocus_mcp/utils/date_filter"
require_relative "omnifocus_mcp/utils/date_formatting"
require_relative "omnifocus_mcp/utils/iso_date"
require_relative "omnifocus_mcp/utils/script_execution"

# Tool param structs (shared by primitives and MCP definitions).
require_relative "omnifocus_mcp/tools/params"
require_relative "omnifocus_mcp/tools/generators"
require_relative "omnifocus_mcp/tools/operations"
require_relative "omnifocus_mcp/tools/presenters"
require_relative "omnifocus_mcp/tools/messages"
require_relative "omnifocus_mcp/tools/generators/list_perspectives"
require_relative "omnifocus_mcp/tools/generators/list_tags"
require_relative "omnifocus_mcp/tools/generators/perspective_view"
require_relative "omnifocus_mcp/tools/generators/query_omnifocus"
require_relative "omnifocus_mcp/tools/generators/query_omnifocus_debug"
require_relative "omnifocus_mcp/tools/generators/database_stats"
require_relative "omnifocus_mcp/tools/generators/add_project"
require_relative "omnifocus_mcp/tools/generators/add_omnifocus_task"
require_relative "omnifocus_mcp/tools/generators/edit_item"
require_relative "omnifocus_mcp/tools/generators/remove_item"
require_relative "omnifocus_mcp/tools/operations/query_omnifocus"
require_relative "omnifocus_mcp/tools/operations/query_omnifocus_debug"
require_relative "omnifocus_mcp/tools/operations/database_stats"
require_relative "omnifocus_mcp/tools/operations/add_omnifocus_task"
require_relative "omnifocus_mcp/tools/operations/add_project"
require_relative "omnifocus_mcp/tools/operations/batch_add_items"
require_relative "omnifocus_mcp/tools/operations/batch_remove_items"
require_relative "omnifocus_mcp/tools/operations/edit_item"
require_relative "omnifocus_mcp/tools/operations/get_perspective_view"
require_relative "omnifocus_mcp/tools/operations/list_perspectives"
require_relative "omnifocus_mcp/tools/operations/list_tags"
require_relative "omnifocus_mcp/tools/operations/remove_item"

# Shared tool support (formatter + stats + helpers) used by definitions.
require_relative "omnifocus_mcp/tools/presenters/batch_report"
require_relative "omnifocus_mcp/tools/presenters/list_perspectives"
require_relative "omnifocus_mcp/tools/presenters/list_tags"
require_relative "omnifocus_mcp/tools/presenters/perspective_view"
require_relative "omnifocus_mcp/tools/presenters/query_reply"
require_relative "omnifocus_mcp/tools/batch_report"
require_relative "omnifocus_mcp/tools/database_stats"
require_relative "omnifocus_mcp/tools/presenters/query_results"
require_relative "omnifocus_mcp/tools/query_omnifocus_formatter"
require_relative "omnifocus_mcp/tools/query_statuses"
require_relative "omnifocus_mcp/tools/definitions/date_formatter"
require_relative "omnifocus_mcp/tools/definitions/key_normalizer"
require_relative "omnifocus_mcp/tools/definitions/mcp_envelope"
require_relative "omnifocus_mcp/tools/definitions/operation_factory"
require_relative "omnifocus_mcp/tools/messages/add_omnifocus_task"
require_relative "omnifocus_mcp/tools/messages/add_project"
require_relative "omnifocus_mcp/tools/messages/batch_remove_items"
require_relative "omnifocus_mcp/tools/messages/edit_item"
require_relative "omnifocus_mcp/tools/messages/list_tools"
require_relative "omnifocus_mcp/tools/messages/remove_item"

# Tool definitions wrap primitives for MCP exposure.
require_relative "omnifocus_mcp/tools/definitions/add_omnifocus_task_tool"
require_relative "omnifocus_mcp/tools/definitions/add_project_tool"
require_relative "omnifocus_mcp/tools/definitions/batch_add_items_tool"
require_relative "omnifocus_mcp/tools/definitions/batch_remove_items_tool"
require_relative "omnifocus_mcp/tools/definitions/edit_item_tool"
require_relative "omnifocus_mcp/tools/definitions/get_perspective_view_tool"
require_relative "omnifocus_mcp/tools/definitions/list_perspectives_tool"
require_relative "omnifocus_mcp/tools/definitions/list_tags_tool"
require_relative "omnifocus_mcp/tools/definitions/query_omnifocus_tool"
require_relative "omnifocus_mcp/tools/definitions/remove_item_tool"

# Resources (base must be loaded before its subclasses).
require_relative "omnifocus_mcp/resources/base"
require_relative "omnifocus_mcp/resources/flagged_resource"
require_relative "omnifocus_mcp/resources/inbox_resource"
require_relative "omnifocus_mcp/resources/perspective_resource"
require_relative "omnifocus_mcp/resources/project_resource"
require_relative "omnifocus_mcp/resources/stats_resource"
require_relative "omnifocus_mcp/resources/today_resource"

# MCP bootstrap depends on everything above.
require_relative "omnifocus_mcp/mcp"
require_relative "omnifocus_mcp/cli"
